[package]
name = "proj1"
version = "0.1.0"
authors = ["annakarenina"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.7.1"
